'use strict';

const { groupByArea, buildTitle } = require('./diff');

/**
 * Build the markdown PR body from diff stats and commit subjects.
 * @param {{ files: Array<{path: string, additions: number, deletions: number}>, subjects: string[], base?: string }} input
 * @returns {string}
 */
function buildBody({ files, subjects, base }) {
  const groups = groupByArea(files);
  const totalAdd = files.reduce((n, f) => n + f.additions, 0);
  const totalDel = files.reduce((n, f) => n + f.deletions, 0);

  const lines = [];
  lines.push('## Summary');
  lines.push('');
  for (const g of groups) {
    const names = g.files.map((f) => `\`${f.path}\``).join(', ');
    const verb = g.area === 'Tests' ? 'cover' : g.area === 'Docs' ? 'document' : 'touch';
    const short = g.files.length <= 3 ? names : `${g.files.length} files (${g.files.slice(0, 3).map((f) => `\`${f.path}\``).join(', ')}, …)`;
    lines.push(`- **${g.area}:** ${verb} ${short}`);
  }
  if (groups.length === 0) lines.push('_No file changes detected._');
  lines.push('');
  lines.push(`**${files.length} file${files.length === 1 ? '' : 's'}** changed, **+${totalAdd} −${totalDel}**`);
  if (base) lines.push(`_base: \`${base}\`_`);
  lines.push('');

  if (subjects && subjects.length > 0) {
    lines.push('## Commits');
    lines.push('');
    for (const s of subjects.slice(0, 20)) lines.push(`- ${s}`);
    lines.push('');
  }

  lines.push('## Checklist');
  lines.push('');
  lines.push('- [ ] Tests added/updated for changed behaviour');
  lines.push('- [ ] Docs/README updated if needed');
  lines.push('- [ ] No new runtime dependencies (project policy)');
  lines.push('');
  lines.push('---');
  lines.push('_Generated by [pr-genie](https://github.com/Dukk11/pr-genie) 🧞_');
  return lines.join('\n');
}

/**
 * Compose the full PR payload (title + body).
 */
function buildPR({ files, subjects, base }) {
  return {
    title: buildTitle(subjects, files),
    body: buildBody({ files, subjects, base }),
  };
}

/**
 * Prompt for an optional Ollama polish pass — pure, no network here.
 */
function buildOllamaPrompt(pr) {
  return [
    'You are writing a pull-request description. Improve clarity and keep the exact markdown structure.',
    'Do not invent changes that are not listed. Keep it under 200 words.',
    '',
    `Title: ${pr.title}`,
    '',
    pr.body,
  ].join('\n');
}

module.exports = { buildBody, buildPR, buildOllamaPrompt };
